global:
  scrape_interval: 10s        # metrics를 수집하는 매 시간(defaul: 60s) 
  evaluation_interval: 60s    # 알람 규칙을 평가하는 간격

scrape_configs:
  - job_name: 'prometheus' # 작업 이름
    static_configs:
      - targets: ['localhost:9091'] # Prometheus 자체를 스크레이핑 대상으로 추가

  - job_name: 'service_name_1'
    static_configs:
      - targets: ['10.251.1.164:10010'] 

  - job_name: 'service_name_2'
    static_configs:
      - targets: ['10.251.1.164:10020'] 

  - job_name: 'service_name_3'
    static_configs:
      - targets: ['10.251.1.164:10030'] 

  - job_name: 'service_name_4'
    static_configs:
      - targets: ['10.251.1.164:10040']