version: "3"
services:
  prometheus:
    image: 'prom/prometheus:v2.48.0'
    container_name: 'prometheus'
    ports: 
      - '9090:9090'
    volumes:
      - ./prometheus_worker.yml:/etc/prometheus/prometheus.yml
    pid: host                 # host의 namespace를 사용
    restart: unless-stopped   # container가 중단되지 않는 한 자동으로 재시작

  node-exporter:
    image: 'prom/node-exporter:v1.7.0'
    container_name: 'node-exporter'
    command:
      - '--collector.hwmon'   # hwmon dashboard를 사용하기 위한 flag
    volumes:
      - '/sys:/host/sys:ro'   # data를 수집하기 위해 `/sys` 위치를 읽기 전용으로 mount(변경 불가능)
    extra_hosts:            
      - 'host.docker.internal:host-gateway'   # container에서 host의 network에 접근하기 위한 설정 (network resource나 service에 접근이 필요시)
    ports:
    - '9100:9100'
    pid: host                 # host의 namespace를 사용
    restart: unless-stopped   # container가 중단되지 않는 한 자동으로 재시작

  dcgm-exporter:
    image: 'nvidia/dcgm-exporter:3.1.8-3.2.0-b0-ubuntu20.04'
    container_name: 'dcgm-exporter'
    ports: 
      - '9400:9400'
    pid: host                 # host의 namespace를 사용
    restart: unless-stopped   # container가 중단되지 않는 한 자동으로 재시작
# docker-compose -f docker-compose_worker.yml up -d
