global:
  scrape_interval: 10s        # metrics를 수집하는 매 시간(defaul: 60s) 

scrape_configs:
  - job_name: 'prometheus' # 작업 이름
    static_configs:
      - targets: ['localhost:9090'] # Prometheus 자체를 스크레이핑 대상으로 추가

  - job_name: 'node_exporter' 
    static_configs:
    # IP:port 형식으로 작성
    # container_name:port 또는 localhost:port 형식으로 하면 동작 X   
    #  - targets: ['192.168.110.18:9100']    


