services:
  redis:
    image: 'redis:7.2.1-alpine'   # alpine: 경량화, 보안성, 성능 최적화, 단순성을 위한 Alpine Linux를 기반 image
    container_name: 'redis'
    ports:
      - '6379:6379'
    
# docker-compose -f docker-compose_utils.yml up -d